// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://hazomlnzobmcvdtycfnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhhem9tbG56b2JtY3ZkdHljZm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTU2MzcsImV4cCI6MjA1OTg3MTYzN30.1JCsZYEvAP9j58tAfjKiuzT4tnOtMioCHcpte0Ke6PY";

// Import the supabase client like this:                
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);